### ISSUE TITLE
Can't get root/access 

### ISSUE THREAD

**Issue by DanSman** [puddly/android-otp-extractor#5] opened 2018-01-07 08:25 UTC
Hey,

Just tried your software.
I have some problems with andotp. I would like to update my RRemix system. After the update I can't use andotp even with the plan backups.

Anyway..
I tried your software and a pop up popped up and I gave it access. It stopped with 
`Checking for root. You might have to grant ADB temporary root access.
Unknown id: TEST
Root not found!
.` 
But I can get access with adb shell.

Can I use a command to get my 2fa accounts showed up in my browser or something?
I tried to read your code but I'm not good at this. Adb shell as well. 

So, root and adb access is available.

Thanks
 
Edit:
Sry, just saw there are already 2 closed issues.
I read this https://github.com/puddly/android-otp-extractor/pull/3 but I don't really understand this.

**Comment by puddly** [comment] 2018-01-10 05:21
@DanSman This might be caused by quoting issues with `adb`. I don't know how to replicate the issue, but I just pushed a commit that should fix it.

Note that if you can't get AndOTP's exporting feature to work, this application won't help you at all. AndOTP encrypts its database with a key stored in Android's keystore, which I haven't yet found a way to work with using just `adb` commands. All that will happen is that AndOTP's backup activity will open and you'll be asked for the path to the JSON file you exported.

**Comment by DanSman** [comment] 2018-01-12 01:54
Hi,

thanks for the reply.

I had to delete/ uncomment this line 
`#    subprocess.check_output(['adb', 'shell', 'su', '-c', "am start -n org.shadowice.flocke.andotp/.Activities.BackupActivity"])`
It was possible to read the backup, then. 

So, now I get following lines of my acc ...
`otpauth://totp/
otpauth://totp/
.....`
Is it possible to get the QR code with it? 

The andotp restore doesn't work on my RRemix update for some reason. So, I stuck with an older system. That means I can do backups of the andotp app but I can't restore them after the RRemix update. Now, I'm thinking to get the QR codes to scan the QR code manually in the app again.

Thanks,
Dan

**Comment by puddly** [comment] 2018-01-12 01:57
@DanSman What happens if you don't comment that line out?

As for generating QR codes, please look at the README or `extract_otp_tokens.py --help`. There is a `--show-qr` argument.

**Comment by DanSman** [comment] 2018-01-12 02:13
Thanks.

What I have to add to the line?
`sudo python3.6 extract_otp_tokens.py --show-qr`

My web browser starts but it's completely empty. It seems to be the software doesn't take the andotp backup.

**Comment by puddly** [comment] 2018-01-12 02:15
@DanSman If it printed `otpauth://` lines, your backup was read just fine. Are you running it with `--andotp`?

**Comment by DanSman** [comment] 2018-01-12 02:19
Yes. I changed the default storage in the file and uncomment the line above.

I get `otpauth://` printed.

**Comment by puddly** [comment] 2018-01-12 02:26
@DanSman I was using some ES6-only JavaScript syntax, which might not be compatible with your default browser. I just pushed a fix that should make the webpage show up.

**Closed by puddly** 2018-01-12 02:26 UTC
